/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BankAccountCreateNestedManyWithoutClientsInput } from "./BankAccountCreateNestedManyWithoutClientsInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { EmailCreateNestedManyWithoutClientsInput } from "./EmailCreateNestedManyWithoutClientsInput";
import { PhoneNumberCreateNestedManyWithoutClientsInput } from "./PhoneNumberCreateNestedManyWithoutClientsInput";

@InputType()
class ClientCreateInput {
  @ApiProperty({
    required: false,
    type: () => BankAccountCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => BankAccountCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => BankAccountCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  bankAccounts?: BankAccountCreateNestedManyWithoutClientsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfBirth?: Date | null;

  @ApiProperty({
    required: false,
    type: () => EmailCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => EmailCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => EmailCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  emails?: EmailCreateNestedManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string | null;

  @ApiProperty({
    required: false,
    type: () => PhoneNumberCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => PhoneNumberCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => PhoneNumberCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  phoneNumbers?: PhoneNumberCreateNestedManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}

export { ClientCreateInput as ClientCreateInput };
