/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BankAccountUpdateManyWithoutClientsInput } from "./BankAccountUpdateManyWithoutClientsInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { EmailUpdateManyWithoutClientsInput } from "./EmailUpdateManyWithoutClientsInput";
import { PhoneNumberUpdateManyWithoutClientsInput } from "./PhoneNumberUpdateManyWithoutClientsInput";

@InputType()
class ClientUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BankAccountUpdateManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => BankAccountUpdateManyWithoutClientsInput)
  @IsOptional()
  @Field(() => BankAccountUpdateManyWithoutClientsInput, {
    nullable: true,
  })
  bankAccounts?: BankAccountUpdateManyWithoutClientsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfBirth?: Date | null;

  @ApiProperty({
    required: false,
    type: () => EmailUpdateManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => EmailUpdateManyWithoutClientsInput)
  @IsOptional()
  @Field(() => EmailUpdateManyWithoutClientsInput, {
    nullable: true,
  })
  emails?: EmailUpdateManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string | null;

  @ApiProperty({
    required: false,
    type: () => PhoneNumberUpdateManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => PhoneNumberUpdateManyWithoutClientsInput)
  @IsOptional()
  @Field(() => PhoneNumberUpdateManyWithoutClientsInput, {
    nullable: true,
  })
  phoneNumbers?: PhoneNumberUpdateManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}

export { ClientUpdateInput as ClientUpdateInput };
